# DIAP Noir Circuit - Prover Inputs
# Public inputs (known to verifier)
expected_did_hash = [123, 116]  # CID multi-hash part
public_key_hash = 23781          # Public key hash
nonce_hash = 6699              # Nonce hash

# Private inputs (secret witness)
secret_key = [252, 93]        # Secret key parts
did_document_hash = [123, 116] # DID document hash
nonce = [99, 66]             # Nonce parts
